-- Guarda uma cópia dos dados da edição de Jantar Harmonizado toda vez que ela
-- é atualizada ("Editar edição" ou "Nova edição"), pra dar pro painel mostrar
-- histórico de edições anteriores. Não mexe em eventos_especiais nem em como
-- o bot lê a edição atual — só arquiva o estado anterior antes do update.
create table if not exists eventos_especiais_historico (
  id bigint generated by default as identity primary key,
  evento_id bigint not null,
  nome text not null,
  titulo text,
  valor_pessoa numeric not null,
  data_evento date not null,
  ativo boolean not null default true,
  imagem_url text,
  cota_vagas integer,
  arquivado_em timestamptz not null default now()
);

create index if not exists eventos_especiais_historico_evento_id_idx
  on eventos_especiais_historico (evento_id);
