-- Modelos de mensagem reutilizáveis pra Conversas (ícone acima do composer).
-- Por enquanto só "texto" é usado na UI — imagem/áudio ficam no schema já
-- prontos (coluna midia_url) pra quando o envio de mídia pelo Painel for
-- implementado (depende de mudar o workflow n8n de envio, que hoje só
-- aceita texto puro).

create table if not exists modelos_mensagem (
  id bigint generated by default as identity primary key,
  nome text not null,
  tipo text not null default 'texto' check (tipo in ('texto', 'imagem', 'audio')),
  conteudo text,
  midia_url text,
  created_at timestamptz not null default now()
);

alter table modelos_mensagem enable row level security;
