-- Aba "Atendimento Presencial": clientes que comem no restaurante sem
-- reserva prévia. `criado_em` é a própria data/hora do preenchimento (não é
-- campo do formulário, vem do default now() do insert). Itens guardam nome
-- e preço "snapshot" do momento do pedido — não seguem o preço vivo do
-- cardápio se ele mudar depois.

create table if not exists pedidos_presenciais (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references clientes(id),
  criado_em timestamptz not null default now(),
  observacao text,
  total numeric not null default 0,
  responsavel_user_id uuid
);

create table if not exists pedidos_presenciais_itens (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references pedidos_presenciais(id) on delete cascade,
  cardapio_item_id bigint references cardapio_itens(id),
  nome_item text not null,
  preco_unitario numeric not null,
  quantidade integer not null default 1
);

alter table pedidos_presenciais enable row level security;
alter table pedidos_presenciais_itens enable row level security;
