-- Fatos base do restaurante (endereço, horários, políticas, etc.) — hoje só
-- existem na planilha que alimenta o RAG do bot. Guardamos aqui como passo
-- temporário até decidirem se migram de vez pra cá; o RAG continua sendo
-- alimentado separadamente por enquanto.
create table if not exists perfil_restaurante (
  id bigint generated by default as identity primary key,
  categoria text not null,
  topico text not null,
  informacao text not null,
  ordem integer not null default 0,
  created_at timestamptz not null default now()
);

alter table perfil_restaurante enable row level security;
