-- Fatos base do restaurante (endereço, horários, políticas, etc.) que
-- alimentam o RAG do bot — editáveis pela tela "Regras e comandos" do
-- Painel, com reindexação automática (ver src/lib/rag/reindex-perfil.ts).
create table if not exists perfil_restaurante (
  id bigint generated by default as identity primary key,
  categoria text not null,
  topico text not null,
  informacao text not null,
  ordem integer not null default 0,
  created_at timestamptz not null default now()
);

alter table perfil_restaurante enable row level security;
