-- Reservas do espaço de eventos (2º andar, capacidade 80 pessoas) — pra
-- aniversários, casamentos, corporativo etc. com 10+ pessoas. Fica vinculado
-- a um cliente já existente na base (clientes), igual as reservas normais.
create table if not exists eventos_reservas (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references clientes(id),
  nome_evento text not null,
  tipo text,
  data date not null,
  horario time,
  pessoas integer not null default 10,
  espaco text not null default '2º andar',
  observacao text,
  status text not null default 'pendente' check (status in ('pendente', 'confirmado', 'cancelado')),
  responsavel_user_id uuid,
  created_at timestamptz not null default now()
);

create index if not exists eventos_reservas_cliente_id_idx on eventos_reservas (cliente_id);
create index if not exists eventos_reservas_data_idx on eventos_reservas (data);

alter table eventos_reservas enable row level security;
