-- Histórico de handoff bot/humano, pra metrificar (quantas vezes, quem
-- assumiu, duração, se foi o bot que pediu ajuda ou o cliente que pediu).
-- Antes só existia o estado atual no Redis (TTL 1h, sem histórico).

create table if not exists handoff_eventos (
  id bigint generated by default as identity primary key,
  telefone text not null,
  tipo text not null check (tipo in ('iniciado', 'finalizado')),
  status text null check (status in ('humano', 'atencao')),
  origem text not null check (origem in ('painel', 'bot', 'cliente')),
  staff_user_id uuid null,
  staff_nome text null,
  criado_em timestamptz not null default now()
);

create index if not exists idx_handoff_eventos_telefone on handoff_eventos(telefone, criado_em desc);
create index if not exists idx_handoff_eventos_criado_em on handoff_eventos(criado_em desc);

alter table handoff_eventos enable row level security;
